# Generated by Django 2.0.6 on 2018-06-23 11:48

from django.db import migrations, models
import django.db.models.deletion
from rooms_reservation.models import *


def populate(apps, schema_editor):
    Room.objects.create(name="Filetowa", capacity=30, projector=True)
    Room.objects.create(name="Żółta", capacity=23, projector=True)
    Room.objects.create(name="Czarna", capacity=10, projector=True)
    Room.objects.create(name="Szara", capacity=52, projector=False)
    Room.objects.create(name="Zielona", capacity=17, projector=True)
    Room.objects.create(name="Czerwona", capacity=28, projector=True)
    Room.objects.create(name="Biała", capacity=44, projector=False)
    Room.objects.create(name="Pomarańczowa", capacity=38, projector=True)
    Room.objects.create(name="Niebieska", capacity=7, projector=True)
    Room.objects.create(name="Różowa", capacity=21, projector=False)


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate),
    ]